server:
  port: 8082

spring:
  application:
    name: catalog-service

eureka:
  client:
    service-url:
      defaultZOne:  http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
 