server:
  port : 8082
spring:
  application:
    name: catalog-service
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#Configuracion de Actuator
management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

#Configuración de Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      catalogGenre:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true  
#Configuración del mecanismo de reintentos
  retry:
    instances:
      catalogGenre:
        maxAttempts: 3
        waitDuration: 3000
        retryExceptions:
          - feign.FeignException$InternalServerError


