server:
  port : 8082
spring:
  application:
    name: catalog-service
  sleuth:
    sampler:
    probability: 1.0
  rabbitmq:
    addresses: localhost:15672
    virtual-host: app_vhost
    username: guest
    password: guest
  zipkin:
    baseUrl: http://localhost:9410/
    enabled: true
    sender:
      type: rabbit
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#Configuracion de Actuator
management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

#Configuración de Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      catalogGenre:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true  
#Configuración del mecanismo de reintentos
  retry:
    instances:
      catalogGenre:
        maxAttempts: 3
        waitDuration: 3000
        retryExceptions:
          - feign.FeignException$InternalServerError


