server:
  port : 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  sleuth:
    sampler:
    probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    username: root
    password: DevJson21

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true