server:
  port : 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  sleuth:
    sampler:
    probability: 1.0
  #Cambiando el hostname por el que levanta el docker-compose.yml
  zipkin:
    baseUrl: http://zipkin:9411/
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    username: root
    password: DevJson21
  rabbitmq:
    host: rabbit-mq
    port: 5672
    username: guest
    password: guest
queue:
  movie:
    name: queueMovie
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true