server:
  port : 8083
spring:
  application:
    name: serie-service
  datasource:
    mongodb:
      host: localhost
      port: 27017
      database: Netflix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always